import express from 'express';
import createSubscription from '../../services/subscription/createSubscription/createSubscription';
import authenticationToken from '../../middleware/authentication/authenToken';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { pushNotificationSchema, subscriptionSchema } from '../../utils/validator';
import pushNotification from '../../services/subscription/pushNotification/pushNotification';
const router = express.Router();
router.post('/create-subscription',authenticationToken, globalValidator(subscriptionSchema), createSubscription);
router.post('/push-notification', authenticationToken, globalValidator(pushNotificationSchema), pushNotification);
export default router;
