import express from 'express';
import authenticationToken from '../../middleware/authentication/authenToken';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { updateUserProfileValidationSchema, userProfileValidationSchema } from '../../utils/validator';
import createUserProfile from '../../services/profile/createProfile/createProfile';
import updateUserProfile from '../../services/profile/updateProfile/updateProfile';
import deleteUserProfile from '../../services/profile/deleteProfile/deleteProfile';
const router = express.Router();
router.post('/create-profile', authenticationToken, globalValidator(userProfileValidationSchema), createUserProfile);
router.put('/update-profile/:id', authenticationToken, globalValidator(updateUserProfileValidationSchema), updateUserProfile);
router.delete('/delete-profile/:id', authenticationToken, deleteUserProfile);
export default router;