import express from 'express';
import createAccount from '../../serviceImpls/user/register/register.impls';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { updateUserValidationSchema, userLoginValidationSchema, userValidationSchema } from '../../utils/validator';
import authenticationToken from '../../middleware/authentication/authenToken';
import signin from '../../serviceImpls/user/login/login.impls';
import userLogout from '../../serviceImpls/user/logout/logout.impl';
import showUsers from '../../serviceImpls/user/showUsers/showUser.impl';
import showUser from '../../serviceImpls/user/showUser/showUser.impl';
import updateUser from '../../serviceImpls/user/updateUser/updateUser.impl';
const router = express.Router();
router.post('/create-account', globalValidator(userValidationSchema), createAccount);
router.post('/login', globalValidator(userLoginValidationSchema), signin);
router.post('/logout', userLogout);
router.get('/show-users', showUsers);
router.get('/show-user/:id', showUser);
router.put('/update-account/:id', globalValidator(updateUserValidationSchema), updateUser);
export default router;