import express from 'express';
import createAccount from '../../serviceImpls/user/register/register.impls';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { userLoginValidationSchema, userValidationSchema } from '../../utils/validator';
import authenticationToken from '../../middleware/authentication/authenToken';
import signin from '../../serviceImpls/user/login/login.impls';
import userLogout from '../../serviceImpls/user/logout/logout.impl';
const router = express.Router();
router.post('/create-account', globalValidator(userValidationSchema), createAccount);
router.post('/login', globalValidator(userLoginValidationSchema), signin);
router.post('/logout', userLogout);
export default router;